### ISSUE TITLE
Enhancement - Fish

### ISSUE THREAD

**Issue by flytomoon88** [TeraProxy/Essentials#10]
Hi,
would it be able to add having  Fish Buff as well (eg Cat Fish) where buff ID is 70226 and item id is ID: 149367?
or would there be a separate MOD to assign the required buff like different fishes?

**Comment by TeraProxy** [comment]
In theory that's very easy to add but I don't really want to include more than the "essential" buffs in the module which I consider being nostrum and crystal bind.
I feel like adding more items would be unhealthy and too much automation.
