### ISSUE TITLE
Doesnt work in EU after Patch82

### ISSUE THREAD

**Issue by Peckspas** [TeraProxy/Essentials#12]
Doesnt work anymore after Patch82 today on EU. 
![1](https://user-images.githubusercontent.com/49212609/58507529-40918e00-8192-11e9-81c0-a003069fd91f.PNG)
![2](https://user-images.githubusercontent.com/49212609/58507535-45564200-8192-11e9-928f-fcbc85523ae0.PNG)

**Comment by TeraProxy** [comment]
Thanks. I needed to update it for the new patch indeed! Gonna push an update now.

**Comment by TeraProxy** [comment]
Should be fixed. I hope I didn't break anything ;) Couldn't test

**Comment by madeezzy48** [comment]
This problem did not dare to ru  server =(
