### ISSUE TITLE
CCB issue on EU

### ISSUE THREAD

**Issue by ghost** [TeraProxy/Essentials#2]
Hello, the CCB system don't work, he never active CCB when mine is out of CD.

I have item (ID 70000) on my inventory but he never use him!

If you can try to fix it, will be nice 😃 
Good Job and Ty ;)

**Comment by TeraProxy** [comment]
Can you make sure that the CCB on EU has the same item ID? The only other explanation could be that the abnormality ID is different on EU but I doubt that. I currently don't have the EU client so I can't test it personally.

**Comment by ghost** [comment]
Yes i'm sure this is same.

And your last update, for godess don't work too. The mod used my nostrum when i used my godess. :(

**Comment by TeraProxy** [comment]
Fixed the goddess issue in the latest update.
The CCB should work just fine if the item is the normal Complete Crystalbind. 
If it's still bugged, please reopen this.
