### ISSUE TITLE
Crystal Blind

### ISSUE THREAD

**Issue by flytomoon88** [TeraProxy/Essentials#7]
Hi,
 can you add the crystal blind for 4612 as well (I changed to include 4612 but it got reverted when i restarted)
thanks!

**Comment by TeraProxy** [comment]
Hi, sure that shouldn't be much of an issue. Which Crystalbind gives you that abnormality?

**Comment by flytomoon88** [comment]
1 hour cannot traded one , item no should be 4612

**Comment by TeraProxy** [comment]
Hi @flytomoon88 ,

I just added checking for that abnormality. Essentials will not try to keep using a CCB while you are under the influence of the 4612 abnormality.

I have not included automated use of the 1 hour CCB yet. I plan on pushing another update later today that will allow you to set the item you want to use in the config file.

**Comment by TeraProxy** [comment]
Update is live. You can now change the used Crystalbind item by entering its ID in the config file.
